name: Weather Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fcaccuracy
        run: ./fc_accuracy.sh
      - name: rxpoc
        run: ./rxpoc.sh

        
      
