name: Weather Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: retrieve Obs temp and forecast temp
        run: ./rx_poc.sh
      - name: Find accuracy and add to table
        run: ./fc_accuracy.sh

        
      
